config/routes.rb
Siphon::Application.routes.draw do
  resources :users
  resources :sessions,  only: [:new, :create, :destroy]
  resources :videos,    only: [:new, :create, :show, :destroy]
  root to: 'site_index#home'

  match "/upload",  to: 'videos#new',         via: 'get'
  match "/login",   to: 'sessions#new',       via: 'get'
  match "/logout",  to: 'sessions#destroy',   via: 'delete'
  match "/join",    to: 'users#new',          via: 'get'

  get "site_index/search"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :videos

  before_create :create_remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 60 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, length: { minimum: 6 }

  #has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1::hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }

  has_attached_file :name, :styles => {
      :mp4medium => { :geometry => "640x480", :format => 'mp4', streaming: true, processors: [:ffmpeg, :qtfaststart] },
      :oggmedium => { :geometry => "640x480", :format => 'webm', streaming: true, processors: [:ffmpeg] },
      :flvmedium => { :geometry => "640x480", :format => 'flv', streaming: true, processors: [:ffmpeg], :convert_options => { :input => {}, :output => {'c:v' => 'libx264', ar: '22050', crf: '28', vprofile: 'high', preset: 'medium', 'b:v' => '750k', maxrate: '750k', bufsize: '1500k', pix_fmt: 'yuv420p', 'b:a' => '128k', strict: '-2'}} },
      :thumb => { :geometry => "296x166#", :format => 'jpg', :time => 7 }
  }

  validates :name, presence: true

=begin
  def is_mp4video?
    name.instance.name_content_type =~ %r(mp4)
  end
=end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper
  include VideosHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email or password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/site_index_controller.rb
class SiteIndexController < ApplicationController
  def home
    #@user = User.find(1)
    #@video = @user.videos.build
  end

  def login
  end

  def upload
    #@video = @user.videos.find(p)
  end

  def search
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Siphon!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @videos = @user.videos
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def new
    @video = current_user.videos.build if signed_in?
  end

  def create
    if remotipart_submitted?
      @video = current_user.videos.build(video_params)
      respond_to do |format|
        if @video.save
          format.js
          flash[:success] = "Your video has been successfully uploaded!"
          #redirect_to @current_user
        else
          render 'new'
        end
      end
    end
  end

  def show
    @video = Video.find(params[:id])
  end

  def destroy
    @video.destroy
    flash[:success] = "Video deleted successfully!"
    redirect_to @current_user
  end

  private

    def video_params
      params.require(:video).permit(:name)
    end

    def correct_user
      @video = current_user.videos.find_by(id: params[:id])
      redirect_to root_url if @video.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title of page (per-page basis)
  def full_title(page_title)
    base_title = "Siphon, Your Videos At Your Finger Tips"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to login_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
end

app/helpers/site_index_helper.rb
module SiteIndexHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{:href => "#"} &copy Enrique Figueroa
  %nav
    %ul
      %li= link_to "About", '#'

app/views/layouts/_header.html.haml
%header{ :class => "navbar navbar-fixed-top navbar-inverse" }
  %div.navbar-inner
    %div.container
      = link_to "Siphon", root_path, id: "logo"
      %nav
        %ul{:class => "nav span10"}
          - if signed_in?
            %li{:id => "fat-menu", :class => "dropdown"}
              %a{:href => "#", :class => "dropdown-toggle", "data-toggle" => "dropdown"}Me <b class="caret"></b>
              %ul.dropdown-menu
                %li= link_to "Profile", current_user
                %li= link_to "Settings", '#'
                %li.divider
                %li= link_to "Log Out", logout_path, method: "delete"
          - else
            %li= link_to "Join", join_path
            %li= link_to "Log In", login_path
          %li= link_to "Upload", upload_path
          %form{:class => "navbar-search pull-right"}
            %input{:type=> "text", :class => "search-query", :placeholder => "Search"}

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container" id="#main">
      <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(@user.errors.count, 'error')}.
    %ul
      - @user.errors.full_messages.each do |msg|
        %li * #{msg}

app/views/site_index/home.html.haml
%h1 Siphon
%div.center.hero-unit
  %p Watch your videos here.
  = video_tag('/videos/juneau.mp4', size: "600x355", controls: true)
%div
  %ul.thumbnails
    %li.span4
      %a{:href => '#', :class => 'thumbnail'}
        =image_tag('mqdefault.jpg', alt: "Video thumbnail")

app/views/site_index/login.html.haml
-provide(:title, 'Login')
%h1 Login
%p Find me in app/views/site_index/login.html.haml

app/views/site_index/search.html.haml
%h1 SiteIndex#search
%p Find me in app/views/site_index/search.html.haml

app/views/site_index/upload.html.haml
-provide(:title, 'Upload')
%h1 Upload Your Video
%p Rules for uploading
%p.btn.btn-primary &uarr; Upload your video
= form_for @video, :html => { :multipart => true }, :remote => true do |f|
 .field
  = f.label :name
  = f.file_field :name_file_name
 .actions
  = f.submit

app/views/users/new.html.haml
-provide(:title, 'Join')
%h1 Sign up

.row
  .span6.offset3
    = form_for(@user) do |f|
      = render 'shared/error_messages'

      = f.text_field :name, placeholder: "First and Last Name", autofocus: true
      = f.email_field :email, placeholder: "Email Address"
      = f.password_field :password, placeholder: "Password"
      = f.password_field :password_confirmation, placeholder: "Password Confirmation"

      = f.submit "Join", class: "btn btn-large btn-primary"

app/views/users/show.html.haml
-provide(:title, @user.name)
.row
  %aside.span3
    %section
      %h1
        = @user.name
    %section
      %h1
        = gravatar_for @user, size: 150
  .span9
    %h3 #{pluralize(@user.videos.count, 'Video')}
    %ul.thumbnails
      - if @user.videos.any?
        - @user.videos.each do |video|
          %li.span3
            %a{ href: path_to_video("#{video.id}"), class: 'thumbnail' }
              = image_tag video.name.url(:thumb), size: '300x170', alt: ''
              /= video_tag([video.name.url(:mp4medium), video.name.url(:oggmedium)], controls: true)

app/views/videos/_video_uploaded.html.haml
%h2 Success!

app/views/videos/new.html.haml
-provide(:title, 'Upload')
%h1 Upload Your Video
.progress.progress-striped.active{ style: 'display: none' }
  .bar{ style: 'width: 20%' }
.alert.alert-info.span4#rules_explanation
  %p Follow these rules for uploading your video:
  %ol
    %li No copyrighted material allowed
    %li Upload videos you've created yourself

.clearfix
= form_for @video, :html => { :multipart => true }, :remote => true do |f|
  .field
    /= f.label :name, "Upload your video"
    = f.file_field :name
  .actions
    = f.submit "Upload Video", class: "btn btn-big btn-primary"

app/views/videos/show.html.haml
.container.center
  %video{ controls: true }
    %source{ src: @video.name.url(:mp4medium), type: "video/mp4" }
    %source{ src: @video.name.url(:oggmedium), type: "video/webm" }
    %source{ src: @video.name.url(:flvmedium), type: "video/flv" }
  - if current_user?(@video.user)
    %p= link_to "delete", @video, method: :delete, data: { confirm: "Are you sure you want to delete this video?" }, title: 'Delete this video'

%h1 Videos